export const statusCodeToReadableMap = new Map();
// statusCodeToReadableMap.set(100, 'Continue');
// statusCodeToReadableMap.set(101, 'Switching Protocols');
// statusCodeToReadableMap.set(102, 'Processing');
statusCodeToReadableMap.set(200, 'OK');
statusCodeToReadableMap.set(201, 'Created');
// statusCodeToReadableMap.set(202, 'Accepted');
// statusCodeToReadableMap.set(203, 'Non-Authoritative Information');
statusCodeToReadableMap.set(204, 'No Content');
// statusCodeToReadableMap.set(205, 'Reset Content');
// statusCodeToReadableMap.set(206, 'Partial Content');
// statusCodeToReadableMap.set(207, 'Multi-Status');
// statusCodeToReadableMap.set(208, 'Already Reported');
// statusCodeToReadableMap.set(226, 'IM Used');
// statusCodeToReadableMap.set(300, 'Multiple Choices');
// statusCodeToReadableMap.set(301, 'Moved Permanently');
// statusCodeToReadableMap.set(302, 'Found');
// statusCodeToReadableMap.set(303, 'See Other');
// statusCodeToReadableMap.set(304, 'Not Modified');
// statusCodeToReadableMap.set(305, 'Use Proxy');
// statusCodeToReadableMap.set(307, 'Temporary Redirect');
// statusCodeToReadableMap.set(308, 'Permanent Redirect');
statusCodeToReadableMap.set(400, 'Bad Request');
// statusCodeToReadableMap.set(401, 'Unauthorized');
// statusCodeToReadableMap.set(402, 'Payment Required');
// statusCodeToReadableMap.set(403, 'Forbidden');
statusCodeToReadableMap.set(404, 'Not Found');
// statusCodeToReadableMap.set(405, 'Method Not Allowed');
// statusCodeToReadableMap.set(406, 'Not Acceptable');
// statusCodeToReadableMap.set(407, 'Proxy Authentication Required');
// statusCodeToReadableMap.set(408, 'Request Timeout');
// statusCodeToReadableMap.set(409, 'Conflict');
// statusCodeToReadableMap.set(410, 'Gone');
// statusCodeToReadableMap.set(411, 'Length Required');
// statusCodeToReadableMap.set(412, 'Precondition Failed');
// statusCodeToReadableMap.set(413, 'Payload Too Large');
// statusCodeToReadableMap.set(414, 'URI Too Long');
// statusCodeToReadableMap.set(415, 'Unsupported Media Type');
// statusCodeToReadableMap.set(416, 'Range Not Satisfiable');
// statusCodeToReadableMap.set(417, 'Expectation Failed');
// statusCodeToReadableMap.set(418, "I'm a teapot");
// statusCodeToReadableMap.set(421, 'Misdirected Request');
// statusCodeToReadableMap.set(422, 'Unprocessable Entity');
// statusCodeToReadableMap.set(423, 'Locked');
// statusCodeToReadableMap.set(424, 'Failed Dependency');
// statusCodeToReadableMap.set(425, 'Too Early');
// statusCodeToReadableMap.set(426, 'Upgrade Required');
// statusCodeToReadableMap.set(428, 'Precondition Required');
// statusCodeToReadableMap.set(429, 'Too Many Requests');
// statusCodeToReadableMap.set(431, 'Request Header Fields Too Large');
// statusCodeToReadableMap.set(451, 'Unavailable For Legal Reasons');
statusCodeToReadableMap.set(500, 'Internal Server Error');
// statusCodeToReadableMap.set(501, 'Not Implemented');
// statusCodeToReadableMap.set(502, 'Bad Gateway');
// statusCodeToReadableMap.set(503, 'Service Unavailable');
// statusCodeToReadableMap.set(504, 'Gateway Timeout');
// statusCodeToReadableMap.set(505, 'HTTP Version Not Supported');
// statusCodeToReadableMap.set(506, 'Variant Also Negotiates');
// statusCodeToReadableMap.set(507, 'Insufficient Storage');
// statusCodeToReadableMap.set(508, 'Loop Detected');
// statusCodeToReadableMap.set(510, 'Not Extended');
// statusCodeToReadableMap.set(511, 'Network Authentication Required');

export const statusCodes = [...statusCodeToReadableMap.keys()];